from typing import Protocol


class EntityStore(Protocol):
    def save_entities(self, entities: object) -> None: ...

    def load_entities(self) -> object: ...

    def save_observations(self, observations: object) -> None: ...

    def load_observations(self) -> object: ...

    def save_relationships(self, relationships: object) -> None: ...

    def load_relationships(self) -> object: ...


__all__ = ["EntityStore"]
